### ISSUE TITLE
Math edit interface background 

### ISSUE THREAD

**Issue by Sologala** [typora/typora-monospace-theme#5]
![image-20200427091632652](https://tva1.sinaimg.cn/large/007S8ZIlly1ge825y3hlij30o307zdg3.jpg)
the background is too bright .
How can I change edit interface background. or the math font color to make it be more contrastive.

**Comment by abnerlee** [comment]
You can use
```css
:root {
--rawblock-edit-panel-bd: red;
}
```

to change the background color
